[package]
name = "reward-pool"
version = "1.0.0"
authors = ["Ryuhei"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.terra.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.8.0" 
cosmwasm-std = { version = "0.16.2" }
terra-cosmwasm = "2.2.0"
terraswap = "2.4.0"
schemars = "0.8.3"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
